
plugins:
  shop_test_enabled:
    default: true
    client: true
  shop_test_strategy:
    default: "all_on"
    client: true
    type: enum
    choices:
      - ssr_prepend
      - ssr_append
      - admin_plugins
      - engine_mount
      - ember_route_map
      - all_on
  shop_test_nav_inject:
    default: "both"
    client: true
    type: enum
    choices:
      - none
      - nav_api
      - nav_connector
      - both
  shop_test_route_prefix:
    default: "shop"
    client: true
